### ISSUE TITLE
Chaoss Slack-bot Content Contributions

### ISSUE THREAD

**Issue by the-techgurl** [chaoss/chaoss-africa#12]
On the topic of improving the Chaoss Slack bot, there is a need for content contributions and the areas needing content include:

1. Slack bot messages
2. Documentation
3. CONTRIBUTING.md, SETUP.md, and README.md files
5. Issue template forms.

Content can be created for any of the above that require new content and tag @Ruth-ikegah to review the pull request.
Suggestions on how to improve already existing content are welcomed, if anyone would like to take any of these do create an [issue](https://github.com/chaoss/chaoss-slack-bot/issues/new/choose) and tag @mispee007 to assign it to you.

While creating the issue you can just put N/A in any field that's not applicable to what you're trying to do in the issue form.
If you have any questions, reach out to Precious Abubakar on Slack.
Here's a link to the project [slack-bot/wiki](https://github.com/chaoss/chaoss-slack-bot/wiki)

**Comment by peculiaruc** [comment]
Assign @peculiaruc

**Comment by the-techgurl** [comment]
Hi, @peculiaruc which of these areas would you want to work on?

**Comment by peculiaruc** [comment]
> 3\. CONTRIBUTING.md, SETUP.md, and README.md files
No 3

**Comment by the-techgurl** [comment]
Okay @peculiaruc please create an issue for it, so that it can be assigned to you.

**Comment by ALIPHATICHYD** [comment]
@the-techgurl 
I'd like to ask if this issue is still opened?

**Comment by peculiaruc** [comment]
> @the-techgurl 
> I'd like to ask if this issue is still opened?

No please. The PR is waiting for review.

**Comment by ALIPHATICHYD** [comment]
> > @the-techgurl
> > I'd like to ask if this issue is still opened?
> 
> No please. The PR is waiting for review.

Okay thank oyu very much for your reply.
