### ISSUE TITLE
Event Badging Mobile Design

### ISSUE THREAD

**Issue by iamkingsleey** [chaoss/chaoss-africa#14]
We have some screens for the Mobile view we need some UX review and redesign to reduce scroll time for users.

About Event Badging Page Mobile
Event Badging Page Mobile 

Details will be made available to contributors who express interest.

**Comment by Shubh-all** [comment]
Hi, I'm Interested!

**Comment by iamkingsleey** [comment]
Awesome @Shubh-all

**Comment by iamkingsleey** [comment]
You should have access to the workspace now. Check the mobile page [here](https://www.figma.com/file/7tiuJbwakgDu15mOjzKTDK/Badging-Website?type=design&node-id=1289-2903&mode=design&t=tfGOLQXfwuvoZ2Ca-0) @Shubh-all

**Comment by BeautyBelz** [comment]
Hello, I'm interested in this, how can I get started
