### ISSUE TITLE
New Month Design

### ISSUE THREAD

**Issue by iamkingsleey** [chaoss/chaoss-africa#16]
Feel free to create stunning New Month designs for the following months;

- October
- November
- December

Will be cool to have one each for CHAOSS Africa and CHAOSS Global.

Some old designs for inspiration:
![Uploading Feb_Holiday_ copy 5.jpg…]()
![March_Holiday_ copy 8](https://github.com/chaoss/chaoss-africa/assets/63562509/7833782d-6b31-4292-992e-d52681997516)
![May](https://github.com/chaoss/chaoss-africa/assets/63562509/aa594f93-1b61-4bdc-8ec6-96f5f5287d20)

**Comment by adelanaofficial** [comment]
Hey @iamkingsleey, kindly assign me to this task.
