### ISSUE TITLE
Design Documentation For CHAOSS Event Badging Project

### ISSUE THREAD

**Issue by iamkingsleey** [chaoss/chaoss-africa#17]
We need a Design Documentation for the DEI Event Badging Project.
A Product Requirement Document will be great to guide design implementation.

I will be here to share any information you need. 👍🏾

**Comment by Delight362** [comment]
Just the desgin for the documentation? Or to design and documents? 
If the first question is yes please provide a guild for it I will work on it.

**Comment by NyiaJoe** [comment]
@Delight362 it involves documentation

**Comment by Delight362** [comment]
Okay on github?

**Comment by NyiaJoe** [comment]
https://www.figma.com/file/7tiuJbwakgDu15mOjzKTDK/Badging-Website?type=design&node-id=698-2448&mode=design
