### ISSUE TITLE
Create An Image for Social Media Post

### ISSUE THREAD

**Issue by olybeke** [chaoss/chaoss-africa#18]
We need an image for our next post on Twitter.

The copy for the design is " What does CHAOSS stands for? "

For any questions kindly let me know. Thanks!

**Comment by adelanaofficial** [comment]
Hey @iamkingsleey, kindly assign me to this task.

**Comment by Delight362** [comment]
Have this issues been worked on ?

**Comment by adelanaofficial** [comment]
> Have this issues been worked on ?

Hello @Delight362, I would love if you could help? Connect with me on slack, please?

**Comment by NyiaJoe** [comment]
@Delight362 From earlier conversation, it has been assigned. I'll get back to you on this if it has not been completed.

Thank you.

**Comment by NyiaJoe** [comment]
> Have this issues been worked on ?

No. Can you take this on?

**Comment by Delight362** [comment]
Okay what's the content,?

**Comment by Busayo-ojo** [comment]
@iamkingsleey Can this be closed?
