### ISSUE TITLE
Add Folder structure for all CHAOSS Africa Focus Groups

### ISSUE THREAD

**Issue by Ruth-ikegah** [chaoss/Chaoss-Africa#2]

**Comment by FaithKovi** [comment]
@Ruth-ikegah I will like to work on this. Please assign.

**Comment by Stevecmd** [comment]
Hello @Ruth-ikegah is this issue still open? If so, kindly explain further as to the requirements, thank you!

**Comment by Ruth-ikegah** [comment]
Hi @Stevecmd, Thanks for indicating interest! @FaithKovi is already working on this issue. 

You can join the CHAOSS check here for some open issues (Under the To Do Section): https://github.com/orgs/badging/projects/4

**Comment by Stevecmd** [comment]
Thanks! @Ruth-ikegah
