### ISSUE TITLE
Create A Design For AMA Session 

### ISSUE THREAD

**Issue by olybeke** [chaoss/chaoss-africa#21]
We need a design for our upcoming AMA session happening on X space.

Copy for design: AMA session with Chaoss Africa. 
Date: 29th September, 2023
Time: 6pm WAT 

Kindly note that we will start making publicity with the design, on the 25th September.  If there's any question, please do well to leave them here. Thanks for contributing!

**Comment by olybeke** [comment]
Yes, it has done @Busayo-ojo

**Comment by Busayo-ojo** [comment]
Thanks Oluchi!
