### ISSUE TITLE
Create  a background for CHAOSS Education Course Video Recording 

### ISSUE THREAD

**Issue by peculiaruc** [chaoss/chaoss-africa#24]
We need a background that will be used while recording CHaoss Education Video

Sample: 
![image](https://github.com/user-attachments/assets/d2e8df29-6d07-4862-9b0e-f85543056a4c)

**Comment by peculiaruc** [comment]
Hi @iamkingsleey, CHAOSS Education needs a background to be used for all video recordings. Kindly help,

**Comment by iamkingsleey** [comment]
![Video-Background](https://github.com/user-attachments/assets/31b359c4-5e6b-4f01-b229-0d4b346e47fa)
![Video-Background-Light](https://github.com/user-attachments/assets/d4f5252a-0fef-43c8-ad84-7a8f27132480)
@peculiaruc

**Comment by peculiaruc** [comment]
> Member

Thank you so much @iamkingsleey . These look awesome. I like them. 
One last thing, Could you please add Education in front of CHAOSS
This "CHAOSS Education"

**Comment by Busayo-ojo** [comment]
@peculiaruc I think this would be a good issue for hacktoberfest contributions.

Ask contributors to add Education in front WDYT?

**Comment by peculiaruc** [comment]
This issue has been completed. Please help me close it

**Comment by Busayo-ojo** [comment]
Great, closing now
