### ISSUE TITLE
Suggestion: A resource file and glossary file for new contributors

### ISSUE THREAD

**Issue by Giftea** [chaoss/chaoss-africa#45]
For Newcomers, iot would be useful to have a glossary that explains key terms or acronyms frequently use in the the project (like, OSS, CHAOSS, WG, UN, metrics e.t.c)

**Comment by harmonyelendu** [comment]
@Giftea thank you for your suggestion. This has been done and added, see file [here](https://github.com/chaoss/chaoss-africa/blob/main/CHAOSS%20Glossary.md)

**Comment by Giftea** [comment]
Thanks @harmonyelendu
