### ISSUE TITLE
Create Image for Social Media Post

### ISSUE THREAD

**Issue by Ruth-ikegah** [chaoss/Chaoss-Africa#5]
Problem: We need an image for our next Twitter thread on Open Source Alternative tools

Solution: Check this [document](https://docs.google.com/document/d/1bFHU4H6wtGGSCImnR2St8_bAMVCODz9AwiP46hNFAFI/edit?usp=sharing), the text labelled in red is the thread we want to create the image for. It would be great if the designer could play with the logos of the different tools on the design.

A similar image we have created in the past: https://twitter.com/chaoss_africa/status/1603346592597262340?s=46&t=nqcSPG0qLrEVxdAEyOPh1g

Have questions tag @Ruth-ikegah

**Comment by iamkingsleey** [comment]
Noted @Ruth-ikegah

**Comment by Delight362** [comment]
Can I work on this @iamkingsleey

**Comment by Delight362** [comment]
@iamkingsleey please check out this one's https://docs.google.com/document/d/1DwE5Wzb6g0drAzKSKeN-eXI4qeVUuS652hMkE9ZpGts/edit?usp=drivesdk

**Comment by iamkingsleey** [comment]
Hi @Delight362, thank you for indicating interest in picking this up. 
I have taken a look at it. Great concepts, however, I developed a template last year to guide and make the design consistent. Sophia used it to make this https://www.figma.com/file/7tiuJbwakgDu15mOjzKTDK/Badging-Website?node-id=2059%3A5286&t=6VnCBuvi9WzTHsTp-0 the previous Twitter thread, I think it will be best to maintain that consistency. Check out the Figma link, I belive it will be helpful. Also, the font style used for the design is SORA; You will find the font file here https://drive.google.com/drive/folders/1r5iqmnuj8-vqqsrD_b2sPggDGIEwLMUN?usp=sharing

**Comment by Delight362** [comment]
Okay thanks for this information

**Comment by Ruth-ikegah** [comment]
@Delight362, thanks for your work so far!

Something to note: We just need one image for the thread

**Comment by NyiaJoe** [comment]
@Ruth-ikegah Could you check this and kindly drop your feedback? Thanks
![Twitter thread-open-source-alternatives](https://user-images.githubusercontent.com/34577709/216814137-f50b9502-e42c-4dcd-a63a-62bd52599872.png)

**Comment by Delight362** [comment]
Thanks for the reminder @Ruth-ikegah and @iamkingsleey  you can check out the update here.
https://www.figma.com/proto/7tiuJbwakgDu15mOjzKTDK/Badging-Website?node-id=2603%3A6206&scaling=scale-down&page-id=2511%3A5846

**Comment by Ruth-ikegah** [comment]
This looks awesome @Delight362 

Thanks so much! I will be posing this tomorrow on our social.
