### ISSUE TITLE
Typo and Grammar Corrections Needed in Glossary File

### ISSUE THREAD

**Issue by Giftea** [chaoss/chaoss-africa#53]
I have found some typos and grammatical errors in the Glossary file that need to be corrected. Below are the proposed corrections:

1. **Current:**
   - "holitic" → **Correction:** "holistic"
   - "understaning" → **Correction:** "understanding"
   - "Acronym" → **Correction:** "Acronyms"
   - "Mark Down" → **Correction:** "Markdown"
   - "Linus Foundation" → **Correction:** "Linux Foundation"
   - "FOSSDEM" → **Correction:** "FOSDEM"
   - "africa" → **Correction:** "Africa"
   - OSCAR → **Correction:** "OSCA"
   
2. Additional small fixes:
   - "MIT;" should use a colon: "MIT:"
   - Add corresponding word (Meeting) to FOSDEM
   - Remove the stray "d" in "Focus Group d"
   - Remove the unnecessary dash at the end.

**Comment by Giftea** [comment]
Please assign to me and add "documentation" and "hacktoberfest" labels @Busayo-ojo @harmonyelendu

**Comment by harmonyelendu** [comment]
Thank you for Spotting @Giftea
