### ISSUE TITLE
Grammatical errors in DocScavenger.md need correcting

### ISSUE THREAD

**Issue by Young-W1** [chaoss/chaoss-africa#55]
I noticed grammatical errors in the [DocScavenger.md](https://github.com/chaoss/chaoss-africa/blob/main/Hacktoberfest/DocScavanger.md) file. 

Errors and proposed changes: 

- Support | Reviewer's. [Proposed change: reviewers]

- Share, Comments and Support Posts that involves Doc Scavenger. [Proposed change: Share, Comment, and Support Posts that involve Doc Scavenger. ]

- Once it's assigned you can kick off. [Proposed change: Once it's assigned, you can kick off.]

- Slack: Communication Center and conversation.  [Proposed change: ... for conversation]

- The following resources has been provided just for you!. [Proposed change: The following resources have been provided just for you!]

**Comment by harmonyelendu** [comment]
Thank you for spotting, Changes have been effected
