### ISSUE TITLE
Create Image for Social Media

### ISSUE THREAD

**Issue by iamkingsleey** [chaoss/Chaoss-Africa#7]
Problem: We need an image for our next Twitter thread on "Why contribute to open source?"

Solution: Check this [document](https://docs.google.com/document/d/16t3dDOKANl1me_Ji8Gh8mnns89X_Rej23eJiGUDdch0/edit?usp=sharing), 

A similar image we have created in the past: https://twitter.com/chaoss_africa/status/1603346592597262340?s=46&t=nqcSPG0qLrEVxdAEyOPh1g

Have questions tag @iamkingsleey

**Comment by NyiaJoe** [comment]
@iamkingsleey I'll love to get into this

**Comment by NyiaJoe** [comment]
@iamkingsleey I'll love to get into this

**Comment by iamkingsleey** [comment]
Okay great [NyiaJoe](https://github.com/NyiaJoe)

**Comment by Ruth-ikegah** [comment]
Hi @NyiaJoe, I have assigned this issue to you!

**Comment by NyiaJoe** [comment]
Sure, @Ruth-ikegah

**Comment by iamkingsleey** [comment]
Thank you @NyiaJoe. Create job! I think I prefer the second concept. Though I am stuck with interpreting the icon; Not sure it best represents the idea of contribution. Just my thought... Lol, What do you think? @Ruth-ikegah

**Comment by iamkingsleey** [comment]
Okay, @Ruth-ikegah has accepted the second design @NyiaJoe.
Thank you!
