### ISSUE TITLE
Data Visualization Design.

### ISSUE THREAD

**Issue by iamkingsleey** [chaoss/Chaoss-Africa#8]
We have a document that summarizes the results of our recent survey on Open Source Software Challenges in Africa. To make the data more easily understood and impactful, we aim to create a visually appealing design that effectively represents the data sets. Below is the document you can work with.
[CHAOSS AFRICA 2022 survey.pdf](https://github.com/chaoss/Chaoss-Africa/files/10721316/CHAOSS.AFRICA.2022.survey.pdf)

Don't hesitate to reach out if you need more context.

**Comment by NyiaJoe** [comment]
@iamkingsleey I want to jump on this

**Comment by iamkingsleey** [comment]
Great! @NyiaJoe. Let's see the magic you make. Thank you

**Comment by NyiaJoe** [comment]
[CHAOSS.pdf](https://github.com/chaoss/Chaoss-Africa/files/10744439/CHAOSS.pdf)
@iamkingsleey Kindly go through this, it is the first design before iteration

**Comment by iamkingsleey** [comment]
I Didn't expect it so soon ...Lol. Thank you so much @NyiaJoe Let me check it out

**Comment by Teebarh** [comment]
Oh my God @NyiaJoe, your visualization is so good!

**Comment by NyiaJoe** [comment]
[CHAOSS.pdf](https://github.com/chaoss/Chaoss-Africa/files/10861645/CHAOSS.pdf)
@iamkingsleey Kindly go through this iteration. I expect your feedback. Thanks

**Comment by iamkingsleey** [comment]
This is beautiful @NyiaJoe. Great Job!!!
