### ISSUE TITLE
Happy New Month Design

### ISSUE THREAD

**Issue by iamkingsleey** [chaoss/Chaoss-Africa#9]
Make a design for the New Month for CHAOSS Global and CHAOSS AFRICA.

**Comment by iamkingsleey** [comment]
@Ruth-ikegah What are your thoughts on these?

![March_Holiday_ copy 8](https://user-images.githubusercontent.com/63562509/222024904-e18ab05f-a47a-453b-b854-debb1277c2f5.jpg)
![March_Holiday_ copy 7](https://user-images.githubusercontent.com/63562509/222024922-df109fa9-67bc-4b3a-9c18-d0af7dd99ef2.jpg)

**Comment by Ruth-ikegah** [comment]
It's really cool! I love the concept
